name: email_client
description: This package provides the contract (EmailClient) that concrete implementations (e.g., SMTP, AWS SES, SendGrid clients) should adhere to.
repository: https://github.com/flutter-news-app-full-source-code/email-client
publish_to: none

environment:
  sdk: ^3.9.0

dependencies: 
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0
